name: bluebook
version: 1.0.0.0
github: pbrisbin/bluebook
license: MIT
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com

extra-doc-files:
  - README.md
  - CHANGELOG.md

description: Please see <https://github.com/pbrisbin/bluebook#readme>

dependencies:
  - base >= 4 && < 5

ghc-options:
  - -fwrite-ide-info
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-local-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-unsafe
  - -optP-Wno-nonportable-include-path # workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies

library:
  source-dirs: src
  dependencies:
    - Blammo
    - blaze-html
    - envparse
    - errors
    - exceptions
    - extra
    - file-embed
    - filepath
    - http-api-data
    - microlens-platform
    - mtl
    - optparse-applicative
    - pandoc
    - pandoc-types
    - relude
    - unliftio
    - unliftio-core
    - xdg-basedir
    - zlib

executables:
  bluebook:
    main: Main.hs
    source-dirs: app
    dependencies:
      - bluebook
      - optparse-applicative
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - bluebook
      - hspec
