name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-cache-action@v2
      - id: stack
        uses: freckle/stack-action@v3
      - uses: freckle/weeder-action@v2
        with:
          ghc-version: ${{ steps.stack.outputs.compiler-version }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/hlint-setup@v2
      - uses: haskell/actions/hlint-run@v2
        with:
          fail-on: warning

  image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata-action@v4
        with:
          images: pbrisbin/bluebook

      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action
        with:
          cache-from: "type=gha"
          cache-to: "type=gha"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
