name: Pages

on:
  push:
    branches: "main"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: _site
          key: v1-${{ runner.os }}-pages

      - uses: freckle/stack-cache-action@v2
      - id: stack
        uses: freckle/stack-action@v3
        with:
          stack-arguments: --copy-bins

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Create bluebook(1)
        run: make doc.install PANDOC=pandoc

      - name: Generate site
        run: |
          mkdir -p _site
          ${{ steps.stack.outputs.local-bin }}/bluebook -C _site
        env:
          HTML_ROOT: /bluebook/

      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: _site
      - id: deployment
        uses: actions/deploy-pages@v1
